<?php

/**************************
/
/ Problem 2 (http://projecteuler.net/problem=2)
/
/ "Each new term in the Fibonacci sequence is 
/ generated by adding the previous two terms. 
/ By starting with 1 and 2, the first 10 terms 
/ will be:
/ 
/ 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
/ 
/ By considering the terms in the Fibonacci 
/ sequence whose values do not exceed four 
/ million, find the sum of the even-valued 
/ terms."
/
**************************/

$running = true; // true until number exceeds maximum
$maximum = 4000000; // stop after this number
$metCriteria = array(1, 2); // all numbers that meet criteria
$sum = 0; // sum of all numbers that met criteria

while ($running) {
	// calculate next number in Fibonacci sequence
	$len = count($metCriteria);
	$nextNumber = $metCriteria[$len-1] + $metCriteria[$len-2];
	
	if ($nextNumber > $maximum) {
		// exceeded maximum, stopping
		$running = false;
	} else {
		// add to $metCriteria
		array_push($metCriteria, $nextNumber);
	}
}

// find sum of all numbers which met the criteria
// and happen to be EVEN numbers
$len = count($metCriteria);
for ($i=0; $i<count($metCriteria); $i++) {
	if ($metCriteria[$i] % 2 == 0) $sum += $metCriteria[$i];
}

echo $sum;

?>