<?php
function getTime()
    {
    $a = explode (' ',microtime());
    return(double) $a[0] + $a[1];
    }
$Start = getTime();
?>





<?php

/**************************
/
/ The sequence of triangle numbers is generated by
/ adding the natural numbers. So the 7th triangle
/ number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
/ The first ten terms would be:
/
/ 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
/
/ Let us list the factors of the first seven
/ triangle numbers:
/
/  1: 1
/  3: 1,3
/  6: 1,2,3,6
/ 10: 1,2,5,10
/ 15: 1,3,5,15
/ 21: 1,3,7,21
/ 28: 1,2,4,7,14,28
/ We can see that 28 is the first triangle number
/ to have over five divisors.
/
/ What is the value of the first triangle number
/ to have over five hundred divisors?
/
/ Solution: 76576500
/ Running-time: ~22 secs
/
**************************/

set_time_limit( 30 );

function divisorCount( $number ) {

    $count = 0;

    $limit = floor( sqrt( $number ) );

    for( $i = 1; $i <= $limit; $i ++) {

        if( $number % $i == 0 ) $count++;

    }

    return $count * 2;

}

echo "<pre>";

// Number of divisors we are looking for.
$divisors = 500;

$triangle = 1;

for( $i = 1; divisorCount( $triangle ) <= $divisors; $i++, $triangle += $i );

echo "Answer: $triangle is the first triangle number "
   . "to have over $divisors divisors.";

echo "</pre>";

?>






<?php
$End = getTime();
echo "Time taken = ".number_format(($End - $Start),2)." secs";
?>