<?php
function getTime()
    {
    $a = explode (' ',microtime());
    return(double) $a[0] + $a[1];
    }
$Start = getTime();
?>





<?php

/**************************
/
/ The sequence of triangle numbers is generated by
/ adding the natural numbers. So the 7th triangle
/ number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
/ The first ten terms would be:
/
/ 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
/
/ Let us list the factors of the first seven
/ triangle numbers:
/
/  1: 1
/  3: 1,3
/  6: 1,2,3,6
/ 10: 1,2,5,10
/ 15: 1,3,5,15
/ 21: 1,3,7,21
/ 28: 1,2,4,7,14,28
/ We can see that 28 is the first triangle number
/ to have over five divisors.
/
/ What is the value of the first triangle number
/ to have over five hundred divisors?
/
/ Solution: ?
/ Running-time: ?
/
**************************/

set_time_limit(30);

function getTriangleNumber( $n ) {

    $sum = 0;

    for( $i = 1; $i <= $n; $i++ ) $sum += $i;

    return $sum;

}

// Do work here.

echo "<pre>";

$answer = 0;

$limit = 1000;

for( $i = 1; $i < $limit; $i++ ) {

    // Search for first triangle number to have
    // over five hundred divisors here.

    //echo getTriangleNumber( $i ) . "<br>";

}

echo "Answer: $answer";

echo "</pre>";

?>






<?php
$End = getTime();
echo "Time taken = ".number_format(($End - $Start),2)." secs";
?>